export const skillsData = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Vue",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Node.js",
  "Express.js",
  "Three.js",
  "React-Three-Fiber",
  "Redux/Redux-toolkit",
  "React Query",
  "Framer Motion",
  "SCSS",
  "Tailwind",
  "GraphQL",
  "PostgreSQL",
  "Sequelize",
  "Prisma",
  "Jest",
] as const;
